name: projectflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  stylish_bottom_bar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  -images/logo.png
  -images/bg.jpg
  -images/bg-2.png
  -images/bg-3.jpg
  -images/bg-4.png
  -images/kuliner.png
  -images/nongkrong.png
  -images/transportasi.png
  -images/img-1.jpg
  -images/img-1-1.jpg
  -images/img 1-2.jpg
  -images/img-1-3.jpg
  -images/img-2-1.jpg
  -images/img-2-2.jpg
  -images/req1.jpg
  -images/req2.jpg
  -images/req3.jpg
  -images/req4.jpg
  -images/req5.jpg
  -images/req6.jpg

